#!/usr/bin/python3

"""
This script is used to collect data from the camera and lidar.
"""

import rospy
import rosbag
import roslaunch
from det_data_handler.data_handler import DataHandler


class LidarCamCollector(DataHandler):
    def __init__(self, image_topic, lidar_topic):
        super(LidarCamCollector, self).__init__(image_topic)
        self.lidar_topic = lidar_topic

    def run(self):
        pass
        