#!/usr/bin/python3

"""
This script is used to handle both raw images and point clouds
TODO:
1. compute optical flow of images in real time
2. get stationary image frames
3. save stationary images to disk
4. set max number of images to save
"""

import rospy
from det_data_handler.data_handler import DataHandler

if __name__ == '__main__':
    rospy.init_node('data_collection_node')
    ns = rospy.get_namespace()
    image_topic = ns + "/" + ns + "/color/image_raw"
    data_handler = DataHandler(image_topic)
    rospy.spin()
