#!/usr/bin/python3

"""
This script is used to handle datasets with COCO format
"""

import argparse
from det_data_handler.coco_handler import CocoHandler

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='COCO dataset handler')
    parser.add_argument('--dataset_dir', type=str, required=True, help='Dataset directory')
    args = parser.parse_args()
    coco_handler = CocoHandler(args.dataset_dir)
    coco_handler.unzip_tasks(coco_handler.task_dir)
    coco_handler.merge_tasks(coco_handler.task_dir)

